### ISSUE TITLE
Refactor Pages.ts

### ISSUE THREAD

**Issue by ySnoopyDogy** [ySnoopyDogy/MenheraBot#101]
Pra falar a real, a melhor palavra nem é refatorar, e sim APAGAR DELETAR EXCLUIR DESTRUIR DESINTEGRAR E ENTÃO COMEÇAR DO ZERO

Marcos Castro de Silva Teresinha

**Comment by ySnoopyDogy** [comment]
Pages.ts was removed

**Comment by Tsugami** [comment]
nice
