### ISSUE TITLE
Error trying to start

### ISSUE THREAD

**Issue by ySnoopyDogy** [ySnoopyDogy/MenheraBot#106]
Ta com um problema na build que ao tentar ligar, gala que n exister um tal de 'init' la no client, na parte de conectar no sentry, n sei oq é, nunca aconteceu isso, n sei se é questão do codigo ou da build, preciso de verdade de ajuda niso

**Comment by Tsugami** [comment]
solved?

**Comment by ySnoopyDogy** [comment]
yepo
