### ISSUE TITLE
Remove npm install from deployments

### ISSUE THREAD

**Issue by ySnoopyDogy** [ySnoopyDogy/MenheraBot#112]
To usando a versão dev vei, n posso atualizar toda hora, se n ela quebra igual ta quebrada agora

**Comment by Tsugami** [comment]
usa yarn

**Comment by ySnoopyDogy** [comment]
Oq mudaria

**Comment by Tsugami** [comment]
o yarn é mais rápido, seguro e inteligente do que o npm

**Comment by ySnoopyDogy** [comment]
v13 has been released
